var express = require('express');
var app = express();

// async function fetchDataFromQuery(query) {
//     return JSON.parse(
//         `{"metaData":[{"name":"VEHICLE_RELATED_CRIMES_2010"},{"name":"PERCENTAGE_2010"},{"name":"YEAR_2010"},{"name":"VEHICLE_RELATED_CRIMES_2011"},{"name":"PERCENTAGE_2011"},{"name":"YEAR_2011"},{"name":"VEHICLE_RELATED_CRIMES_2012"},{"name":"PERCENTAGE_2012"},{"name":"YEAR_2012"},{"name":"VEHICLE_RELATED_CRIMES_2013"},{"name":"PERCENTAGE_2013"},{"name":"YEAR_2013"},{"name":"VEHICLE_RELATED_CRIMES_2014"},{"name":"PERCENTAGE_2014"},{"name":"YEAR_2014"},{"name":"VEHICLE_RELATED_CRIMES_2015"},{"name":"PERCENTAGE_2015"},{"name":"YEAR_2015"},{"name":"VEHICLE_RELATED_CRIMES_2016"},{"name":"PERCENTAGE_2016"},{"name":"YEAR_2016"},{"name":"VEHICLE_RELATED_CRIMES_2017"},{"name":"PERCENTAGE_2017"},{"name":"YEAR_2017"},{"name":"VEHICLE_RELATED_CRIMES_2018"},{"name":"PERCENTAGE_2018"},{"name":"YEAR_2018"},{"name":"VEHICLE_RELATED_CRIMES_2019"},{"name":"PERCENTAGE_2019"},{"name":"YEAR_2019"},{"name":"VEHICLE_RELATED_CRIMES_2020"},{"name":"PERCENTAGE_2020"},{"name":"YEAR_2020"},{"name":"VEHICLE_RELATED_CRIMES_2021"},{"name":"PERCENTAGE_2021"},{"name":"YEAR_2021"},{"name":"VEHICLE_RELATED_CRIMES_2022"},{"name":"PERCENTAGE_2022"},{"name":"YEAR_2022"}],"rows":[["BURGLARY FROM VEHICLE",8.32095096582467,2010,"BURGLARY FROM VEHICLE",7.200200702458609,2011,"BURGLARY FROM VEHICLE",6.414201183431949,2012,"BURGLARY FROM VEHICLE",6.980273141122909,2013,"BURGLARY FROM VEHICLE",6.543624161073829,2014,"BURGLARY FROM VEHICLE",5.76235541535226,2015,"BURGLARY FROM VEHICLE",7.44616623062991,2016,"BURGLARY FROM VEHICLE",8.19171281267901,2017,"BURGLARY FROM VEHICLE",9.12525977706405,2018,"BURGLARY FROM VEHICLE",8.805998846375699,2019,"BURGLARY FROM VEHICLE",3.93700787401575,2020,null,0,2021,null,0,2022],["RECKLESS DRIVING",0.024764735017335303,2010,"RECKLESS DRIVING",0.0250878073256397,2011,null,0,2012,null,0,2013,"RECKLESS DRIVING",0.0479386385426654,2014,null,0,2015,null,0,2016,null,0,2017,null,0,2018,null,0,2019,null,0,2020,null,0,2021,null,0,2022]]}`
//     )
// }

const oracledb = require("oracledb");
async function fetchDataFromQuery(query) {
    console.log("fetching connection")
  try {
    let connection = await oracledb.getConnection(
      {
        user: "ananya.agrawal",
        password: "",
        connectionString: "(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = oracle.cise.ufl.edu)(PORT = 1521))(CONNECT_DATA=(SID=ORCL)))"
      }
    )
    const data = await connection.execute(query)
    return data
  }

  catch(err){
    console.log(err)
  }
  console.log("Hello!")    
}

var q = `--Query 2
WITH VEHICLE_CRIMES AS
    (SELECT DISTINCT l.CRM_CD_DESC
    FROM WGREGORY.LA_CRIMES l
    WHERE 
--    l.CRM_CD_DESC = 'DRIVING WITHOUT OWNER CONSENT (DWOC)'
--    OR l.CRM_CD_DESC = 'GRAND THEFT / AUTO REPAIR'
--    OR l.CRM_CD_DESC = 'PETTY THEFT - AUTO REPAIR'
--    OR 
    l.CRM_CD_DESC = 'RECKLESS DRIVING'
--    OR l.CRM_CD_DESC = 'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT'
--    OR l.CRM_CD_DESC = 'THEFT FROM MOTOR VEHICLE - ATTEMPT'
--    OR l.CRM_CD_DESC = 'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)'
--    OR l.CRM_CD_DESC = 'THEFT FROM MOTOR VEHICLE - PETTY ($950 ' || chr(38) || ' UNDER)'
--    OR l.CRM_CD_DESC = 'THROWING OBJECT AT MOVING VEHICLE'
--    OR l.CRM_CD_DESC = 'TRAIN WRECKING'
--    OR l.CRM_CD_DESC = 'VEHICLE - ATTEMPT STOLEN'
--    OR l.CRM_CD_DESC = 'VEHICLE - MOTORIZED SCOOTERS, BICYCLES, AND WHEELCHAIRS'
--    OR l.CRM_CD_DESC = 'VEHICLE - STOLEN'
--    OR l.CRM_CD_DESC = 'BIKE - STOLEN'
--    OR l.CRM_CD_DESC = 'BOAT - STOLEN'
    OR
    l.CRM_CD_DESC = 'BURGLARY FROM VEHICLE'
--    OR l.CRM_CD_DESC = 'BURGLARY FROM VEHICLE, ATTEMPTED'
    ),
    DISTRICT_1 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIMES l
    WHERE l.AREA = 1 OR l.AREA = 2 OR l.AREA = 4 OR l.AREA = 11
    ),
    DISTRICT_2 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIMES l
    WHERE l.AREA = 3 OR l.AREA = 12 OR l.AREA = 13 OR l.AREA = 14 OR l.AREA = 18 OR l.AREA = 20
    ),
    DISTRICT_3 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIMES l
    WHERE l.AREA = 6 OR l.AREA = 7 OR l.AREA = 8 OR l.AREA = 9 OR l.AREA = 10 OR l.AREA = 16 OR l.AREA = 17 OR l.AREA = 19 OR l.AREA = 21
    ),
    DISTRICT_4 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIMES l
    WHERE l.AREA = 5
    ),
    DISTRICT_5 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIMES l
    WHERE l.AREA = 15
    )
SELECT DISTINCT r10.VEHICLE_RELATED_CRIMES_2010, NVL(r10.PERCENTAGE_2010, 0) AS PERCENTAGE_2010, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2010')) AS YEAR_2010, r11.VEHICLE_RELATED_CRIMES_2011, NVL(r11.PERCENTAGE_2011, 0) AS PERCENTAGE_2011, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2011')) AS YEAR_2011, r12.VEHICLE_RELATED_CRIMES_2012, NVL(r12.PERCENTAGE_2012, 0) AS PERCENTAGE_2012, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2012')) AS YEAR_2012, r13.VEHICLE_RELATED_CRIMES_2013, NVL(r13.PERCENTAGE_2013, 0) AS PERCENTAGE_2013, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2013')) AS YEAR_2013, r14.VEHICLE_RELATED_CRIMES_2014, NVL(r14.PERCENTAGE_2014, 0) AS PERCENTAGE_2014, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2014')) AS YEAR_2014, r15.VEHICLE_RELATED_CRIMES_2015, NVL(r15.PERCENTAGE_2015, 0) AS PERCENTAGE_2015, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2015')) AS YEAR_2015, r16.VEHICLE_RELATED_CRIMES_2016, NVL(r16.PERCENTAGE_2016, 0) AS PERCENTAGE_2016, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2016')) AS YEAR_2016, r17.VEHICLE_RELATED_CRIMES_2017, NVL(r17.PERCENTAGE_2017, 0) AS PERCENTAGE_2017, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2017')) AS YEAR_2017, r18.VEHICLE_RELATED_CRIMES_2018, NVL(r18.PERCENTAGE_2018, 0) AS PERCENTAGE_2018, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2018')) AS YEAR_2018, r19.VEHICLE_RELATED_CRIMES_2019 AS VEHICLE_RELATED_CRIMES_2019, NVL(r19.PERCENTAGE_2019, 0) AS PERCENTAGE_2019, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2019')) AS YEAR_2019, r20.VEHICLE_RELATED_CRIMES_2020 AS VEHICLE_RELATED_CRIMES_2020, NVL(r20.PERCENTAGE_2020, 0) AS PERCENTAGE_2020, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2020')) AS YEAR_2020, r21.VEHICLE_RELATED_CRIMES_2021 AS VEHICLE_RELATED_CRIMES_2021, NVL(r21.PERCENTAGE_2021, 0) AS PERCENTAGE_2021, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2021')) AS YEAR_2021, r22.VEHICLE_RELATED_CRIMES_2022 AS VEHICLE_RELATED_CRIMES_2022, NVL(r22.PERCENTAGE_2022, 0) AS PERCENTAGE_2022, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2022')) AS YEAR_2022
FROM WGREGORY.LA_CRIMES l,
    WGREGORY.VEHICLE_CRIMES vc
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2010, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2010
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2010' AND l.DATE_RPTD <= '31-DEC-2010' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2010' AND l.DATE_RPTD <= '31-DEC-2010' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2010' AND l.DATE_RPTD <= '31-DEC-2010' AND l.DATE_RPTD IS NOT NULL
    ) r10 ON vc.CRM_CD_DESC = r10.VEHICLE_RELATED_CRIMES_2010
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2011, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2011
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2011' AND l.DATE_RPTD <= '31-DEC-2011' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2011' AND l.DATE_RPTD <= '31-DEC-2011' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2011' AND l.DATE_RPTD <= '31-DEC-2011' AND l.DATE_RPTD IS NOT NULL
    ) r11 ON vc.CRM_CD_DESC = r11.VEHICLE_RELATED_CRIMES_2011
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2012, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2012
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2012' AND l.DATE_RPTD <= '31-DEC-2012' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2012' AND l.DATE_RPTD <= '31-DEC-2012' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2012' AND l.DATE_RPTD <= '31-DEC-2012' AND l.DATE_RPTD IS NOT NULL
    ) r12 ON vc.CRM_CD_DESC = r12.VEHICLE_RELATED_CRIMES_2012
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2013, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2013
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2013' AND l.DATE_RPTD <= '31-DEC-2013' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2013' AND l.DATE_RPTD <= '31-DEC-2013' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2013' AND l.DATE_RPTD <= '31-DEC-2013' AND l.DATE_RPTD IS NOT NULL
    ) r13 ON vc.CRM_CD_DESC = r13.VEHICLE_RELATED_CRIMES_2013
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2014, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2014
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2014' AND l.DATE_RPTD <= '31-DEC-2014' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2014' AND l.DATE_RPTD <= '31-DEC-2014' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2014' AND l.DATE_RPTD <= '31-DEC-2014' AND l.DATE_RPTD IS NOT NULL
    ) r14 ON vc.CRM_CD_DESC = r14.VEHICLE_RELATED_CRIMES_2014
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2015, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2015
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2015' AND l.DATE_RPTD <= '31-DEC-2015' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2015' AND l.DATE_RPTD <= '31-DEC-2015' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2015' AND l.DATE_RPTD <= '31-DEC-2015' AND l.DATE_RPTD IS NOT NULL
    ) r15 ON vc.CRM_CD_DESC = r15.VEHICLE_RELATED_CRIMES_2015
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2016, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2016
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2016' AND l.DATE_RPTD <= '31-DEC-2016' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2016' AND l.DATE_RPTD <= '31-DEC-2016' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2016' AND l.DATE_RPTD <= '31-DEC-2016' AND l.DATE_RPTD IS NOT NULL
    ) r16 ON vc.CRM_CD_DESC = r16.VEHICLE_RELATED_CRIMES_2016
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2017, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2017
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2017' AND l.DATE_RPTD <= '31-DEC-2017' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2017' AND l.DATE_RPTD <= '31-DEC-2017' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2017' AND l.DATE_RPTD <= '31-DEC-2017' AND l.DATE_RPTD IS NOT NULL
    ) r17 ON vc.CRM_CD_DESC = r17.VEHICLE_RELATED_CRIMES_2017
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2018, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2018
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2018' AND l.DATE_RPTD <= '31-DEC-2018' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2018' AND l.DATE_RPTD <= '31-DEC-2018' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2018' AND l.DATE_RPTD <= '31-DEC-2018' AND l.DATE_RPTD IS NOT NULL
    ) r18 ON vc.CRM_CD_DESC = r18.VEHICLE_RELATED_CRIMES_2018
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2019, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2019
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2019' AND l.DATE_RPTD <= '31-DEC-2019' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2019' AND l.DATE_RPTD <= '31-DEC-2019' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2019' AND l.DATE_RPTD <= '31-DEC-2019' AND l.DATE_RPTD IS NOT NULL
    ) r19 ON vc.CRM_CD_DESC = r19.VEHICLE_RELATED_CRIMES_2019
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2020, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2020
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2020' AND l.DATE_RPTD <= '31-DEC-2020' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2020' AND l.DATE_RPTD <= '31-DEC-2020' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2020' AND l.DATE_RPTD <= '31-DEC-2020' AND l.DATE_RPTD IS NOT NULL
    ) r20 ON vc.CRM_CD_DESC = r20.VEHICLE_RELATED_CRIMES_2020
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2021, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2021
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2021' AND l.DATE_RPTD <= '31-DEC-2021' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2021' AND l.DATE_RPTD <= '31-DEC-2021' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2021' AND l.DATE_RPTD <= '31-DEC-2021' AND l.DATE_RPTD IS NOT NULL
    ) r21 ON vc.CRM_CD_DESC = r21.VEHICLE_RELATED_CRIMES_2021
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2022, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2022
    FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIMES l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2022' AND l.DATE_RPTD <= '31-DEC-2022' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2022' AND l.DATE_RPTD <= '31-DEC-2022' AND l.DATE_RPTD IS NOT NULL
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2022' AND l.DATE_RPTD <= '31-DEC-2022' AND l.DATE_RPTD IS NOT NULL
    ) r22 ON vc.CRM_CD_DESC = r22.VEHICLE_RELATED_CRIMES_2022 `
    
async function parseDataFromQuery(query) {
    const output = await fetchDataFromQuery(query);
    let X = [];
    let Y = [];

    let rows = output['rows'][0];
    for (let i = 0; i < output['metaData'].length; i = i + 3) {
        Y.push(rows[i + 1]);
        X.push(rows[i + 2]);
    }
    return {
        "X_Data": X,
        "Y_Data": Y,
    };
}

app.get('/query_2_data', function (req, res) {
    parseDataFromQuery(q).then((output) => {
        res.end(JSON.stringify(output))        
    })
})

var server = app.listen(8081, function () {
   var host = server.address().address
   var port = server.address().port
   console.log("Example app listening at http://%s:%s", host, port)
})