require('dotenv').config()

var express = require('express');
var app = express();

const oracledb = require("oracledb");
const user = process.env.REACT_APP_USERNAME;
const password = process.env.REACT_APP_PW;

async function fetchDataFromQuery(query) {
    console.log("fetching connection")
  try {
    let connection = await oracledb.getConnection(
      {
        user: user,
        password: password,
        connectionString: "(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = oracle.cise.ufl.edu)(PORT = 1521))(CONNECT_DATA=(SID=ORCL)))"
      }
    )
    const data = await connection.execute(query)
    return data
  }

  catch(err){
    console.log(err)
  }
  console.log("Hello!")    
}

var count = `SELECT COUNT(CRM_CD) FROM WGREGORY.LA_CRIME`

var q1 = ``

var q2 = `--Query 2
WITH VEHICLE_CRIMES AS
    (SELECT DISTINCT l.CRM_CD_DESC
    FROM WGREGORY.LA_CRIME l
    WHERE 
--    l.CRM_CD_DESC = 'DRIVING WITHOUT OWNER CONSENT (DWOC)'
--    OR l.CRM_CD_DESC = 'GRAND THEFT / AUTO REPAIR'
--    OR l.CRM_CD_DESC = 'PETTY THEFT - AUTO REPAIR'
--    OR 
    l.CRM_CD_DESC = 'RECKLESS DRIVING'
--    OR l.CRM_CD_DESC = 'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT'
--    OR l.CRM_CD_DESC = 'THEFT FROM MOTOR VEHICLE - ATTEMPT'
--    OR l.CRM_CD_DESC = 'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)'
--    OR l.CRM_CD_DESC = 'THEFT FROM MOTOR VEHICLE - PETTY ($950 ' || chr(38) || ' UNDER)'
--    OR l.CRM_CD_DESC = 'THROWING OBJECT AT MOVING VEHICLE'
--    OR l.CRM_CD_DESC = 'TRAIN WRECKING'
--    OR l.CRM_CD_DESC = 'VEHICLE - ATTEMPT STOLEN'
--    OR l.CRM_CD_DESC = 'VEHICLE - MOTORIZED SCOOTERS, BICYCLES, AND WHEELCHAIRS'
--    OR l.CRM_CD_DESC = 'VEHICLE - STOLEN'
--    OR l.CRM_CD_DESC = 'BIKE - STOLEN'
--    OR l.CRM_CD_DESC = 'BOAT - STOLEN'
    OR
    l.CRM_CD_DESC = 'BURGLARY FROM VEHICLE'
--    OR l.CRM_CD_DESC = 'BURGLARY FROM VEHICLE, ATTEMPTED'
    ),
    DISTRICT_1 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIME l
    WHERE l.AREA = 1 OR l.AREA = 2 OR l.AREA = 4 OR l.AREA = 11
    ),
    DISTRICT_2 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIME l
    WHERE l.AREA = 3 OR l.AREA = 12 OR l.AREA = 13 OR l.AREA = 14 OR l.AREA = 18 OR l.AREA = 20
    ),
    DISTRICT_3 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIME l
    WHERE l.AREA = 6 OR l.AREA = 7 OR l.AREA = 8 OR l.AREA = 9 OR l.AREA = 10 OR l.AREA = 16 OR l.AREA = 17 OR l.AREA = 19 OR l.AREA = 21
    ),
    DISTRICT_4 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIME l
    WHERE l.AREA = 5
    ),
    DISTRICT_5 AS
    (SELECT DISTINCT l.AREA
    FROM WGREGORY.LA_CRIME l
    WHERE l.AREA = 15
    )
SELECT DISTINCT r10.VEHICLE_RELATED_CRIMES_2010, NVL(r10.PERCENTAGE_2010, 0) AS PERCENTAGE_2010, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2010')) AS YEAR_2010, r11.VEHICLE_RELATED_CRIMES_2011, NVL(r11.PERCENTAGE_2011, 0) AS PERCENTAGE_2011, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2011')) AS YEAR_2011, r12.VEHICLE_RELATED_CRIMES_2012, NVL(r12.PERCENTAGE_2012, 0) AS PERCENTAGE_2012, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2012')) AS YEAR_2012, r13.VEHICLE_RELATED_CRIMES_2013, NVL(r13.PERCENTAGE_2013, 0) AS PERCENTAGE_2013, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2013')) AS YEAR_2013, r14.VEHICLE_RELATED_CRIMES_2014, NVL(r14.PERCENTAGE_2014, 0) AS PERCENTAGE_2014, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2014')) AS YEAR_2014, r15.VEHICLE_RELATED_CRIMES_2015, NVL(r15.PERCENTAGE_2015, 0) AS PERCENTAGE_2015, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2015')) AS YEAR_2015, r16.VEHICLE_RELATED_CRIMES_2016, NVL(r16.PERCENTAGE_2016, 0) AS PERCENTAGE_2016, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2016')) AS YEAR_2016, r17.VEHICLE_RELATED_CRIMES_2017, NVL(r17.PERCENTAGE_2017, 0) AS PERCENTAGE_2017, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2017')) AS YEAR_2017, r18.VEHICLE_RELATED_CRIMES_2018, NVL(r18.PERCENTAGE_2018, 0) AS PERCENTAGE_2018, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2018')) AS YEAR_2018, r19.VEHICLE_RELATED_CRIMES_2019 AS VEHICLE_RELATED_CRIMES_2019, NVL(r19.PERCENTAGE_2019, 0) AS PERCENTAGE_2019, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2019')) AS YEAR_2019, r20.VEHICLE_RELATED_CRIMES_2020 AS VEHICLE_RELATED_CRIMES_2020, NVL(r20.PERCENTAGE_2020, 0) AS PERCENTAGE_2020, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2020')) AS YEAR_2020, r21.VEHICLE_RELATED_CRIMES_2021 AS VEHICLE_RELATED_CRIMES_2021, NVL(r21.PERCENTAGE_2021, 0) AS PERCENTAGE_2021, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2021')) AS YEAR_2021, r22.VEHICLE_RELATED_CRIMES_2022 AS VEHICLE_RELATED_CRIMES_2022, NVL(r22.PERCENTAGE_2022, 0) AS PERCENTAGE_2022, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2022')) AS YEAR_2022
FROM WGREGORY.LA_CRIME l,
    WGREGORY.VEHICLE_CRIMES vc
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2010, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2010
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2010' AND l.DATE_RPTD <= '31-DEC-2010' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2010' AND l.DATE_RPTD <= '31-DEC-2010' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2010' AND l.DATE_RPTD <= '31-DEC-2010' AND l.DATE_RPTD IS NOT NULL
    ) r10 ON vc.CRM_CD_DESC = r10.VEHICLE_RELATED_CRIMES_2010
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2011, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2011
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2011' AND l.DATE_RPTD <= '31-DEC-2011' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2011' AND l.DATE_RPTD <= '31-DEC-2011' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2011' AND l.DATE_RPTD <= '31-DEC-2011' AND l.DATE_RPTD IS NOT NULL
    ) r11 ON vc.CRM_CD_DESC = r11.VEHICLE_RELATED_CRIMES_2011
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2012, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2012
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2012' AND l.DATE_RPTD <= '31-DEC-2012' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2012' AND l.DATE_RPTD <= '31-DEC-2012' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2012' AND l.DATE_RPTD <= '31-DEC-2012' AND l.DATE_RPTD IS NOT NULL
    ) r12 ON vc.CRM_CD_DESC = r12.VEHICLE_RELATED_CRIMES_2012
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2013, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2013
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2013' AND l.DATE_RPTD <= '31-DEC-2013' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2013' AND l.DATE_RPTD <= '31-DEC-2013' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2013' AND l.DATE_RPTD <= '31-DEC-2013' AND l.DATE_RPTD IS NOT NULL
    ) r13 ON vc.CRM_CD_DESC = r13.VEHICLE_RELATED_CRIMES_2013
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2014, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2014
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2014' AND l.DATE_RPTD <= '31-DEC-2014' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2014' AND l.DATE_RPTD <= '31-DEC-2014' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2014' AND l.DATE_RPTD <= '31-DEC-2014' AND l.DATE_RPTD IS NOT NULL
    ) r14 ON vc.CRM_CD_DESC = r14.VEHICLE_RELATED_CRIMES_2014
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2015, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2015
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2015' AND l.DATE_RPTD <= '31-DEC-2015' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2015' AND l.DATE_RPTD <= '31-DEC-2015' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2015' AND l.DATE_RPTD <= '31-DEC-2015' AND l.DATE_RPTD IS NOT NULL
    ) r15 ON vc.CRM_CD_DESC = r15.VEHICLE_RELATED_CRIMES_2015
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2016, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2016
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2016' AND l.DATE_RPTD <= '31-DEC-2016' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2016' AND l.DATE_RPTD <= '31-DEC-2016' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2016' AND l.DATE_RPTD <= '31-DEC-2016' AND l.DATE_RPTD IS NOT NULL
    ) r16 ON vc.CRM_CD_DESC = r16.VEHICLE_RELATED_CRIMES_2016
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2017, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2017
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2017' AND l.DATE_RPTD <= '31-DEC-2017' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5 
        WHERE l.DATE_RPTD >= '01-JAN-2017' AND l.DATE_RPTD <= '31-DEC-2017' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2017' AND l.DATE_RPTD <= '31-DEC-2017' AND l.DATE_RPTD IS NOT NULL
    ) r17 ON vc.CRM_CD_DESC = r17.VEHICLE_RELATED_CRIMES_2017
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2018, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2018
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2018' AND l.DATE_RPTD <= '31-DEC-2018' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2018' AND l.DATE_RPTD <= '31-DEC-2018' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2018' AND l.DATE_RPTD <= '31-DEC-2018' AND l.DATE_RPTD IS NOT NULL
    ) r18 ON vc.CRM_CD_DESC = r18.VEHICLE_RELATED_CRIMES_2018
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2019, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2019
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2019' AND l.DATE_RPTD <= '31-DEC-2019' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2019' AND l.DATE_RPTD <= '31-DEC-2019' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2019' AND l.DATE_RPTD <= '31-DEC-2019' AND l.DATE_RPTD IS NOT NULL
    ) r19 ON vc.CRM_CD_DESC = r19.VEHICLE_RELATED_CRIMES_2019
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2020, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2020
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2020' AND l.DATE_RPTD <= '31-DEC-2020' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2020' AND l.DATE_RPTD <= '31-DEC-2020' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2020' AND l.DATE_RPTD <= '31-DEC-2020' AND l.DATE_RPTD IS NOT NULL
    ) r20 ON vc.CRM_CD_DESC = r20.VEHICLE_RELATED_CRIMES_2020
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2021, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2021
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2021' AND l.DATE_RPTD <= '31-DEC-2021' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2021' AND l.DATE_RPTD <= '31-DEC-2021' AND l.DATE_RPTD IS NOT NULL
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2021' AND l.DATE_RPTD <= '31-DEC-2021' AND l.DATE_RPTD IS NOT NULL
    ) r21 ON vc.CRM_CD_DESC = r21.VEHICLE_RELATED_CRIMES_2021
    LEFT JOIN
    (SELECT DISTINCT c.CRIME AS VEHICLE_RELATED_CRIMES_2022, ((c.OCCURRENCE / s.SUMMATION) * 100) AS PERCENTAGE_2022
    FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5,
        (SELECT DISTINCT SUM(c.OCCURRENCE) AS SUMMATION
        FROM 
            (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
            FROM WGREGORY.LA_CRIME l, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
            WHERE l.DATE_RPTD >= '01-JAN-2022' AND l.DATE_RPTD <= '31-DEC-2022' AND l.DATE_RPTD IS NOT NULL
            --District selection from filter would go here as one of these:
            AND l.AREA = d1.AREA
            --AND l.AREA = d2.AREA
            --AND l.AREA = d3.AREA
            --AND l.AREA = d4.AREA
            --AND l.AREA = d5.AREA
            GROUP BY l.CRM_CD_DESC
            ) c
        ) s,
        (SELECT DISTINCT l.CRM_CD_DESC AS CRIME, COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIME l, WGREGORY.VEHICLE_CRIMES vc, WGREGORY.DISTRICT_1 d1, WGREGORY.DISTRICT_2 d2, WGREGORY.DISTRICT_3 d3, WGREGORY.DISTRICT_4 d4, WGREGORY.DISTRICT_5 d5
        WHERE l.DATE_RPTD >= '01-JAN-2022' AND l.DATE_RPTD <= '31-DEC-2022' AND l.DATE_RPTD IS NOT NULL
        --District selection from filter would go here as one of these:
        AND l.AREA = d1.AREA
        --AND l.AREA = d2.AREA
        --AND l.AREA = d3.AREA
        --AND l.AREA = d4.AREA
        --AND l.AREA = d5.AREA
        AND l.CRM_CD_DESC = vc.CRM_CD_DESC
        GROUP BY l.CRM_CD_DESC
        ) c
    WHERE c.CRIME = l.CRM_CD_DESC AND l.DATE_RPTD >= '01-JAN-2022' AND l.DATE_RPTD <= '31-DEC-2022' AND l.DATE_RPTD IS NOT NULL
    ) r22 ON vc.CRM_CD_DESC = r22.VEHICLE_RELATED_CRIMES_2022`

var q3 = ``

var q4 = `--Query 4
WITH TOTAL_OCCURRENCE AS
    (SELECT DISTINCT SUM(c10.OCCURRENCE) AS SUMMATION_10, SUM(c11.OCCURRENCE) AS SUMMATION_11, SUM(c12.OCCURRENCE) AS SUMMATION_12, SUM(c13.OCCURRENCE) AS SUMMATION_13, SUM(c14.OCCURRENCE) AS SUMMATION_14, SUM(c15.OCCURRENCE) AS SUMMATION_15, SUM(c16.OCCURRENCE) AS SUMMATION_16, SUM(c17.OCCURRENCE) AS SUMMATION_17, SUM(c18.OCCURRENCE) AS SUMMATION_18, SUM(c19.OCCURRENCE) AS SUMMATION_19
    FROM
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2010' AND l.DATE_OCC <= '31-DEC-2010' AND l.DATE_OCC IS NOT NULL
        ) c10,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2011' AND l.DATE_OCC <= '31-DEC-2011' AND l.DATE_OCC IS NOT NULL
        ) c11,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2012' AND l.DATE_OCC <= '31-DEC-2012' AND l.DATE_OCC IS NOT NULL
        ) c12,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2013' AND l.DATE_OCC <= '31-DEC-2013' AND l.DATE_OCC IS NOT NULL
        ) c13,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2014' AND l.DATE_OCC <= '31-DEC-2014' AND l.DATE_OCC IS NOT NULL
        ) c14,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2015' AND l.DATE_OCC <= '31-DEC-2015' AND l.DATE_OCC IS NOT NULL
        ) c15,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2016' AND l.DATE_OCC <= '31-DEC-2016' AND l.DATE_OCC IS NOT NULL
        ) c16,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2017' AND l.DATE_OCC <= '31-DEC-2017' AND l.DATE_OCC IS NOT NULL
        ) c17,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2018' AND l.DATE_OCC <= '31-DEC-2018' AND l.DATE_OCC IS NOT NULL
        ) c18,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM  WGREGORY.LA_CRIMES l
        WHERE l.DATE_OCC >= '01-JAN-2019' AND l.DATE_OCC <= '31-DEC-2019' AND l.DATE_OCC IS NOT NULL
        ) c19
    )
SELECT DISTINCT r10.CRIME_GROUP AS CRIME_GROUP_2010, (r10.OCCURRENCE / t.SUMMATION_10) AS RATIO_2010, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2010')) AS YEAR_2010, r11.CRIME_GROUP AS CRIME_GROUP_2011, (r11.OCCURRENCE / t.SUMMATION_11) AS RATIO_2011, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2011')) AS YEAR_2011, r12.CRIME_GROUP AS CRIME_GROUP_2012, (r12.OCCURRENCE / t.SUMMATION_12) AS RATIO_2012, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2012')) AS YEAR_2012, r13.CRIME_GROUP AS CRIME_GROUP_2013, (r13.OCCURRENCE / t.SUMMATION_13) AS RATIO_2013, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2013')) AS YEAR_2013, r14.CRIME_GROUP AS CRIME_GROUP_2014, (r14.OCCURRENCE / t.SUMMATION_14) AS RATIO_2014, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2014')) AS YEAR_2014, r15.CRIME_GROUP AS CRIME_GROUP_2015, (r15.OCCURRENCE / t.SUMMATION_15) AS RATIO_2015, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2015')) AS YEAR_2015, r16.CRIME_GROUP AS CRIME_GROUP_2016, (r16.OCCURRENCE / t.SUMMATION_16) AS RATIO_2016, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2016')) AS YEAR_2016, r17.CRIME_GROUP AS CRIME_GROUP_2017, (r17.OCCURRENCE / t.SUMMATION_17) AS RATIO_2017, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2017')) AS YEAR_2017, r18.CRIME_GROUP AS CRIME_GROUP_2018, (r18.OCCURRENCE / t.SUMMATION_18) AS RATIO_2018, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2018')) AS YEAR_2018, r19.CRIME_GROUP AS CRIME_GROUP_2019, (r19.OCCURRENCE / t.SUMMATION_19) AS RATIO_2019, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2019')) AS YEAR_2019
FROM TOTAL_OCCURRENCE t,  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2010' AND l.DATE_OCC <= '31-DEC-2010' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r10 ON cg.CRIME_GROUP = r10.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2011' AND l.DATE_OCC <= '31-DEC-2011' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r11 ON cg.CRIME_GROUP = r11.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2012' AND l.DATE_OCC <= '31-DEC-2012' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r12 ON cg.CRIME_GROUP = r12.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2013' AND l.DATE_OCC <= '31-DEC-2013' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r13 ON cg.CRIME_GROUP = r13.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2014' AND l.DATE_OCC <= '31-DEC-2014' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r14 ON cg.CRIME_GROUP = r14.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2015' AND l.DATE_OCC <= '31-DEC-2015' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r15 ON cg.CRIME_GROUP = r15.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2016' AND l.DATE_OCC <= '31-DEC-2016' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r16 ON cg.CRIME_GROUP = r16.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2017' AND l.DATE_OCC <= '31-DEC-2017' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r17 ON cg.CRIME_GROUP = r17.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2018' AND l.DATE_OCC <= '31-DEC-2018' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r18 ON cg.CRIME_GROUP = r18.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
LEFT JOIN
    (SELECT DISTINCT cg.CRIME_GROUP, NVL(COUNT(l.CRM_CD_DESC), 0) AS OCCURRENCE
    FROM  WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
    WHERE l.DATE_OCC >= '01-JAN-2019' AND l.DATE_OCC <= '31-DEC-2019' AND l.DATE_OCC IS NOT NULL AND cg.CRIME_GROUP IS NOT NULL
    --Filter for Premises
    --AND l.PREMIS_DESC = 'ALLEY'
    --AND l.PREMIS_DESC = 'DRIVEWAY'
    --AND l.PREMIS_DESC = 'GARAGE/CARPORT'
    --AND l.PREMIS_DESC = 'GAS STATION'
    --AND l.PREMIS_DESC = 'MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV''S/MOTORHOME'
    --AND l.PREMIS_DESC = 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)'
    --AND l.PREMIS_DESC = 'OTHER BUSINESS'
    --AND l.PREMIS_DESC = 'OTHER PREMISE'
    --AND l.PREMIS_DESC = 'POST OFFICE'
    --AND l.PREMIS_DESC = 'SINGLE FAMILY DWELLING'
    --AND l.PREMIS_DESC = 'STREET'
    --AND l.PREMIS_DESC = 'VEHICLE, PASSENGER/TRUCK'
    
    --Filter for Time Range
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 0 AND EXTRACT(HOUR FROM l.TIME_OCC) < 6
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 6 AND EXTRACT(HOUR FROM l.TIME_OCC) < 12
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 12 AND EXTRACT(HOUR FROM l.TIME_OCC) < 18
    --AND EXTRACT(HOUR FROM l.TIME_OCC) >= 18 AND EXTRACT(HOUR FROM l.TIME_OCC) <= 23
    GROUP BY CRIME_GROUP
    ) r19 ON cg.CRIME_GROUP = r19.CRIME_GROUP AND cg.CRIME_GROUP IS NOT NULL
WHERE cg.CRIME_GROUP IS NOT NULL`

var q5 = `--Query 5      
SELECT DISTINCT ((w10.OCCURRENCE / (w10.OCCURRENCE + a10.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2010, ((a10.OCCURRENCE / (w10.OCCURRENCE + a10.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2010, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2010')) AS YEAR_2010, ((w11.OCCURRENCE / (w11.OCCURRENCE + a11.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2011, ((a11.OCCURRENCE / (w11.OCCURRENCE + a11.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2011, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2011')) AS YEAR_2011, ((w12.OCCURRENCE / (w12.OCCURRENCE + a12.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2012, ((a12.OCCURRENCE / (w12.OCCURRENCE + a12.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2012, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2012')) AS YEAR_2012, ((w13.OCCURRENCE / (w13.OCCURRENCE + a13.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2013, ((a13.OCCURRENCE / (w13.OCCURRENCE + a13.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2013, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2013')) AS YEAR_2013, ((w14.OCCURRENCE / (w14.OCCURRENCE + a14.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2014, ((a14.OCCURRENCE / (w14.OCCURRENCE + a14.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2014, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2014')) AS YEAR_2014, ((w15.OCCURRENCE / (w15.OCCURRENCE + a15.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2015, ((a15.OCCURRENCE / (w15.OCCURRENCE + a15.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2015, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2015')) AS YEAR_2015, ((w16.OCCURRENCE / (w16.OCCURRENCE + a16.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2016, ((a16.OCCURRENCE / (w16.OCCURRENCE + a16.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2016, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2016')) AS YEAR_2016, ((w17.OCCURRENCE / (w17.OCCURRENCE + a17.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2017, ((a17.OCCURRENCE / (w17.OCCURRENCE + a17.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2017, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2017')) AS YEAR_2017, ((w18.OCCURRENCE / (w18.OCCURRENCE + a18.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2018, ((a18.OCCURRENCE / (w18.OCCURRENCE + a18.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2018, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2018')) AS YEAR_2018, ((w19.OCCURRENCE / (w19.OCCURRENCE + a19.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2019, ((a19.OCCURRENCE / (w19.OCCURRENCE + a19.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2019, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2019')) AS YEAR_2019, ((w20.OCCURRENCE / (w20.OCCURRENCE + a20.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2020, ((a20.OCCURRENCE / (w20.OCCURRENCE + a20.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2020, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2020')) AS YEAR_2020, ((w21.OCCURRENCE / (w21.OCCURRENCE + a21.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2021, ((a21.OCCURRENCE / (w21.OCCURRENCE + a21.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2021, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2021')) AS YEAR_2021, ((w22.OCCURRENCE / (w22.OCCURRENCE + a22.OCCURRENCE)) * 100) AS PERCENTAGE_WITHIN_30_DAYS_2022, ((a22.OCCURRENCE / (w22.OCCURRENCE + a22.OCCURRENCE)) * 100) AS PERCENTAGE_AFTER_30_DAYS_2022, EXTRACT(YEAR FROM TO_DATE ('01-JAN-2022')) AS YEAR_2022
FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2010' AND l.DATE_RPTD <= '31-DEC-2010' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w10,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2010' AND l.DATE_RPTD <= '31-DEC-2010' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a10,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2011' AND l.DATE_RPTD <= '31-DEC-2011' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
       --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w11,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2011' AND l.DATE_RPTD <= '31-DEC-2011' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a11,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2012' AND l.DATE_RPTD <= '31-DEC-2012' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w12,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2012' AND l.DATE_RPTD <= '31-DEC-2012' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a12,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2013' AND l.DATE_RPTD <= '31-DEC-2013' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w13,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2013' AND l.DATE_RPTD <= '31-DEC-2013' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a13,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2014' AND l.DATE_RPTD <= '31-DEC-2014' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w14,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2014' AND l.DATE_RPTD <= '31-DEC-2014' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a14,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2015' AND l.DATE_RPTD <= '31-DEC-2015' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w15,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2015' AND l.DATE_RPTD <= '31-DEC-2015' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a15,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2016' AND l.DATE_RPTD <= '31-DEC-2016' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w16,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2016' AND l.DATE_RPTD <= '31-DEC-2016' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a16,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2017' AND l.DATE_RPTD <= '31-DEC-2017' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w17,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2017' AND l.DATE_RPTD <= '31-DEC-2017' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a17,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2018' AND l.DATE_RPTD <= '31-DEC-2018' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w18,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2018' AND l.DATE_RPTD <= '31-DEC-2018' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a18,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2019' AND l.DATE_RPTD <= '31-DEC-2019' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w19,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2019' AND l.DATE_RPTD <= '31-DEC-2019' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a19,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2020' AND l.DATE_RPTD <= '31-DEC-2020' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w20,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2020' AND l.DATE_RPTD <= '31-DEC-2020' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a20,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2021' AND l.DATE_RPTD <= '31-DEC-2021' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w21,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2021' AND l.DATE_RPTD <= '31-DEC-2021' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a21,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2022' AND l.DATE_RPTD <= '31-DEC-2022' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) <= 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) w22,
        (SELECT DISTINCT COUNT(l.CRM_CD_DESC) AS OCCURRENCE
        FROM WGREGORY.LA_CRIMES l LEFT JOIN WGREGORY.CRIME_TYPE ct ON l.CRM_CD_DESC = ct.CRM_CD_DESC LEFT JOIN WGREGORY.CRIME_GROUPINGS cg ON l.CRM_CD_DESC = cg.CRM_CD_DESC
        WHERE l.DATE_RPTD >= '01-JAN-2022' AND l.DATE_RPTD <= '31-DEC-2022' AND l.DATE_RPTD IS NOT NULL
        AND (l.DATE_RPTD - l.DATE_OCC) > 30
        --Filter to select WGREGORY.WGREGORY.CRIME_GROUPINGS. Format: AND (cg.CRIME_GROUP = 'group1' OR cg.CRIME_GROUP = 'group2' OR cg.CRIME_GROUP = 'group3')
        -- AND (
        --OR cg.CRIME_GROUP = 'MINOR CRIMES'
        --OR cg.CRIME_GROUP = 'SERIOUS OR VIOLENT CRIMES AND OFFENSES'
        --OR cg.CRIME_GROUP = 'SEXUAL CRIMES'
        --OR cg.CRIME_GROUP = 'BATTERY OR ASSAULT'
        --OR cg.CRIME_GROUP = 'CHILD ABUSE'
        --OR cg.CRIME_GROUP = 'GUN CRIMES'
        --OR cg.CRIME_GROUP = 'ROBBERY OR THEFT AGAINST A PERSON'
        --OR cg.CRIME_GROUP = 'BURGLARIES, THEFT AND PROPERTY CRIMES'
        --OR cg.CRIME_GROUP = 'VEHICLE RELATED CRIMES'
        --OR cg.CRIME_GROUP = 'DRUGS'
        --OR cg.CRIME_GROUP = 'VULNERABLE ADULT CRIMES'
        --OR cg.CRIME_GROUP = 'WHITE COLLAR CRIME'
        --)
        ) a22


`


async function parseDataFromQuery(query) {
    const output = await fetchDataFromQuery(query);
    console.log(output);
    let X = [];
    let Y = [];

    let rows = output['rows'][0];
    for (let i = 0; i < output['metaData'].length; i = i + 3) {
        Y.push(rows[i + 1]);
        X.push(rows[i + 2]);
    }
    return {
        "X_Data": X,
        "Y_Data": Y,
    };
}

async function parseCountFromQuery(query) { 
    const output = await fetchDataFromQuery(query);
    let rows = output['rows'][0];
    let tupleCount = rows[0];
    
    return{
        "tupleCount": tupleCount,
    };
}

app.get('/count', function (req, res) {
    parseCountFromQuery(count).then((output) => {
        res.end(JSON.stringify(output))        
    })
})

app.get('/query_1_data', function (req, res) {
    parseDataFromQuery(q1).then((output) => {
        res.end(JSON.stringify(output))        
    })
})

app.get('/query_2_data', function (req, res) {
    parseDataFromQuery(q2).then((output) => {
        res.end(JSON.stringify(output))        
    })
})

app.get('/query_3_data', function (req, res) {
    parseDataFromQuery(q3).then((output) => {
        res.end(JSON.stringify(output))        
    })
})

app.get('/query_4_data', function (req, res) {
    parseDataFromQuery(q4).then((output) => {
        res.end(JSON.stringify(output))        
    })
})

app.get('/query_5_data', function (req, res) {
    parseDataFromQuery(q5).then((output) => {
        res.end(JSON.stringify(output))        
    })
})



var server = app.listen(8081, function () {
   var host = server.address().address
   var port = server.address().port
   console.log("Example app listening at http://%s:%s", host, port)
})